### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jackparmer** [jackparmer/VoxelWorld#1]
### Performance

- [ ] [Perf] Don't draw voxels not in view
- [ ] [Perf] Automatically decimate matrices > 64x64
- [ ] [Perf] Investigate toggle for [JAX](https://jax.readthedocs.io/en/latest/jax.numpy.html) or equivalent

### JavaScript/WASM

- [ ] [JS] Port a JS version with the same API using regl and/or https://github.com/pygfx/wgpu-py

### Features

- [ ] [Feat] Support non-cubic matrices
- [ ] [Feat] Support [named colorscales](https://plotly.com/python/builtin-colorscales/) to visualize numpy arrays and matrices
- [ ] [Feat] `color_matrix` support in `themes`
- [ ] [Feat] Pipelines: Parametric ---> Discrete / Solid object model ---> Voxels

### API
- [ ] [API] `Array` or `Plane` API to visualize/animate worlds with 1-voxel-cell thickness
- [ ] [API] `Scenes` API to composite multiple worlds 
- [ ] [API] Ray tracing unlocks: transparency, shadows, reflection, more realistic specularity
- [ ] [API] Serialization/Deserialization UX
